// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EnterQuizIdModal: typeof import('./src/components/EnterQuizIdModal.vue')['default']
    IButton: typeof import('@inkline/inkline')['IButton']
    IInput: typeof import('@inkline/inkline')['IInput']
    ILayout: typeof import('@inkline/inkline')['ILayout']
    ILayoutAside: typeof import('@inkline/inkline')['ILayoutAside']
    ILayoutContent: typeof import('@inkline/inkline')['ILayoutContent']
    ILayoutFooter: typeof import('@inkline/inkline')['ILayoutFooter']
    ILayoutHeader: typeof import('@inkline/inkline')['ILayoutHeader']
    IModal: typeof import('@inkline/inkline')['IModal']
    Layout: typeof import('./src/components/Layout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
